config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :data_crumbs
  resources :warehouses, only: %i[show]
  resources :workflows, only: %i[show] do
    member do
      get :new_feature
      post :create_feature
      post :process_input
    end
  end
  get 'workflows/:id/features/:feature_id', to: 'workflows#show_feature'
  delete 'workflows/:id/workflows_features/:workflows_feature_id', to: 'workflows#delete_workflows_feature'

  resources :prompt_decorators, only: %i[destroy edit update new create]
  resources :features, only: %i[show]

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount Rupert::API => '/api/'
end

app/models/data_crumb.rb
# frozen_string_literal: true

class DataCrumb < ApplicationRecord
  has_neighbors :embedding
  validates :content, presence: true

  belongs_to :warehouse, inverse_of: :data_crumbs
  has_many :users, through: :warehouse

  self.filter_attributes += [:embedding]

  # alternative:
  # after_create_commit -> do
  #   broadcast_prepend_to "data_crumbs",
  #                       partial: "data_crumbs/data_crumb",
  #                       locals: { data_crumb: self },
  #                       target: "data_crumbs"
  # end

  # after_create_commit -> { broadcast_prepend_later_to "data_crumbs" }
  # after_update_commit -> { broadcast_replace_later_to "data_crumbs" }
  # after_destroy_commit -> { broadcast_remove_to "data_crumbs" }

  # broadcasts_to ->(data_crumb) { [data_crumb.warehouse, 'data_crumbs'] }, inserts_by: :prepend

  attribute :feature_id, :integer
end

app/controllers/data_crumbs_controller.rb
# frozen_string_literal: true

class DataCrumbsController < ApplicationController
  before_action :set_data_crumb, only: %i[show edit update destroy]
  before_action :set_warehouse, only: %i[create]
  before_action :set_feature, only: %i[create]

  def index
    @data_crumbs = current_user.data_crumbs.order(created_at: :desc)
  end

  def show; end

  def new
    @data_crumb = DataCrumb.new
  end

  def edit; end

  def create
    @data_crumb = DataCrumbs::Builder.new(
      content: data_crumb_params[:content],
      warehouse: @warehouse
    ).embed_and_initialize

    if @data_crumb.save
      respond_to do |format|
        notice = t('data_crumbs.flash.created')
        format.html { redirect_to data_crumbs_path, notice: }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @data_crumb.update(data_crumb_params)
      respond_to do |format|
        notice = t('data_crumbs.flash.updated')
        format.html { redirect_to data_crumbs_path, notice: }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @data_crumb.destroy
    respond_to do |format|
      notice = t('data_crumbs.flash.destroyed')
      format.html { redirect_to data_crumbs_path, notice: }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def data_crumb_params
    params.require(:data_crumb).permit(:content, :warehouse_id, :feature_id)
  end

  def set_data_crumb
    @data_crumb = DataCrumb.find(params[:id])
  end

  def set_warehouse
    @warehouse = current_warehouses.find_by(id: data_crumb_params[:warehouse_id])
  end

  def set_feature
    @feature = current_features.find_by(id: data_crumb_params[:feature_id])
  end
end

app/views/data_crumbs/_data_crumb.html.erb
<%= turbo_frame_tag data_crumb do %>
  <div class="data-crumb">
    <%= link_to data_crumb.id, data_crumb_path(data_crumb), data: { turbo_frame: '_top' } %>
    <%= data_crumb.content %>
    <%= data_crumb.warehouse.name %>
    <div class="data-crumb__actions">
      <%= button_to 'Delete', data_crumb_path(data_crumb), method: :delete, class: 'btn btn--light' %>
      <%= link_to 'Edit', edit_data_crumb_path(data_crumb), class: 'btn btn--light' %>
    </div>
  </div>
<% end %>

app/views/data_crumbs/_form.html.erb
<%= simple_form_for data_crumb, html: { class: 'quote form' } do |f| %>
  <% if data_crumb.errors.any? %>
    <div class="error-message">
      <%= data_crumb.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :content, input_html: { autofocus: true } %>
  <%= f.collection_select :warehouse_id, current_warehouses, :id, :name, {} %>
  <%= f.collection_select :feature_id, current_features, :id, :name, {} %>
  <%= link_to 'Cancel', data_crumbs_path, class: 'btn btn--light' %>
  <%= f.submit "#{action_name == 'edit' ? 'Update' : 'Create'} Data Crumb", class: 'btn btn--secondary' %>
<% end %>

app/views/data_crumbs/create.turbo_stream.erb
<%= turbo_stream.prepend "data_crumbs", @data_crumb %>
<%= turbo_stream.update DataCrumb.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/data_crumbs/destroy.turbo_stream.erb
<%= turbo_stream.remove @data_crumb %>

app/views/data_crumbs/edit.html.erb
<main class="container">
  <%= link_to sanitize('&larr; Back to Data Crumbs'), data_crumbs_path %>

  <div class="header">
    <h1>Edit Data Crumb</h1>
  </div>

  <%= turbo_frame_tag @data_crumb do %>
    <%= render 'form', data_crumb: @data_crumb %>
  <% end %>
</main>

app/views/data_crumbs/index.html.erb
<% current_warehouses.each do |warehouse| %>
  <%= turbo_stream_from warehouse, "data_crumbs" %>
<% end %>

<main class="container">
  <div class="header">
    <h1>Data Crumbs</h1>
    <%= link_to 'New Data Crumb', new_data_crumb_path,
                data: { turbo_frame: dom_id(DataCrumb.new) },
                class: 'btn btn--primary' %>
  </div>

  <%= turbo_frame_tag DataCrumb.new %>

  <%= turbo_frame_tag 'data_crumbs' do %>
    <%= render @data_crumbs %>
  <% end %>
</main>

app/views/data_crumbs/new.html.erb
<main class="container">
  <%= link_to sanitize('&larr; Back to Data Crumbs'), data_crumbs_path %>

  <div class="header">
    <h1>New Data Crumb</h1>
  </div>

  <%= turbo_frame_tag @data_crumb do %>
    <%= render 'form', data_crumb: @data_crumb %>
  <% end %>
</main>

app/views/data_crumbs/show.html.erb
<main class="container">
  <%= link_to sanitize('&larr; Back to Data Crumbs'), data_crumbs_path %>
  <div class="header">
    <h1>
      <%= @data_crumb.content %>
    </h1>
  </div>
</main>

app/views/data_crumbs/update.turbo_stream.erb
<%= turbo_stream.replace @data_crumb %>
<%= render_turbo_stream_flash_messages %>