config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :data_crumbs
  resources :warehouses, only: %i[show]
  resources :workflows, only: %i[show] do
    member do
      get :new_feature
      post :create_feature
      post :process_input
    end
  end
  get 'workflows/:id/features/:feature_id', to: 'workflows#show_feature'
  delete 'workflows/:id/workflows_features/:workflows_feature_id', to: 'workflows#delete_workflows_feature'

  resources :prompt_decorators, only: %i[destroy edit update new create]
  resources :features, only: %i[show]

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount Rupert::API => '/api/'
end

app/models/workflow.rb
# frozen_string_literal: true

class Workflow < ApplicationRecord
  include Helpers::ValidationHelper

  validates :name, presence: true, uniqueness: true
  validate :name_is_snakecase

  belongs_to :user
  has_many :workflows_features, dependent: :destroy
  has_many :features, through: :workflows_features
end

app/controllers/workflows_controller.rb
# frozen_string_literal: true

class WorkflowsController < ApplicationController
  before_action :set_workflow

  def show
    @features = @workflow.features.priority_ordered
  end

  def new_feature
    @feature = Feature.new
  end

  def show_feature
    @feature = current_features.find(params[:feature_id])
  end

  def create_feature
    feature_id = params[:feature_id]
    Workflows::WorkflowHandler.new(workflow: @workflow).assign_feature(feature_id:, **feature_params)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def delete_workflows_feature
    @workflow.workflows_features.find(params[:workflows_feature_id]).destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  def process_input
    input = process_input_params[:input_text]

    @output = Workflows::WorkflowHandler.new(workflow: @workflow).process_input(input:)

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def process_input_params
    params.permit(:input_text)
  end

  def feature_params
    params.permit(:resource_class, :probability_threshold)
  end

  def set_workflow
    workflow_id = params[:id]
    @workflow = current_user.workflows.find(workflow_id) if workflow_id.present?
  end
end

app/views/workflows/_new_feature_section.html.erb
<%= turbo_frame_tag Feature.new do %>
  <div>
    <%= link_to 'New Feature', new_feature_workflow_path(@workflow), data: { turbo_frame: dom_id(Feature.new) }, class: 'btn btn--primary' %>
  </div>
<% end %>

app/views/workflows/_new_workflow_feature.html.erb
<%= turbo_frame_tag 'new_feature_workflow' do %>
  <%= select_tag :feature_id, options_from_collection_for_select(current_features, :id, :name), {
    include_blank: 'Select a feature',
    data: {
      controller: 'workflows',
      action: 'workflows#featureSelect',
      workflow_id: @workflow.id,
    },
  } %>
<% end %>

app/views/workflows/_test_prompt_form.html.erb
<%= form_with url: process_input_workflow_path(@workflow), method: :post do |f| %>
  <div>
    <p>Test prompt:</p>
    <%= f.text_area :input_text, rows: 5, input_html: { autofocus: true } %>
  </div>
  <div>
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/workflows/_workflow_details.html.erb
<%= turbo_frame_tag "workflow_features#{@workflow.id}" do %>
  <% @workflow.workflows_features.includes(feature: :prompt_decorators).priority_ordered.each do |workflows_feature| %>
    <%= render 'workflow_feature', locals: { workflows_feature: } %>
  <% end %>
<% end %>

app/views/workflows/_workflow_feature.html.erb
<div>
  <% workflows_feature = locals[:workflows_feature] %>
  <% feature = workflows_feature.feature %>

  <div class="warehouse__data_crumb">
    <div class="warehouse__data_crumb__name">
      <div>
        <%= feature.name %>
      </div>
      <div>
        <%= workflows_feature.priority %>
      </div>
      <div>
        <%= workflows_feature.properties %>
      </div>
      <div>
        <% feature.prompt_decorators.priority_ordered.each do |prompt_decorator| %>
          <p>
            <%= prompt_decorator.value %>
          </p>
        <% end %>
      </div>

      <%= button_to 'Delete',
                    "/workflows/#{@workflow.id}/workflows_features/#{workflows_feature.id}",
                    method: :delete,
                    form: { data: { turbo_confirm: 'Sure?' } },
                    class: 'btn btn--primary' %>
    </div>
  </div>
</div>

app/views/workflows/_workflow_feature_form.html.erb
<%= turbo_frame_tag 'new_feature_workflow' do %>
  <%= form_with url: create_feature_workflow_path(@workflow), method: :post do |f| %>
    <div>
      <%= f.collection_select :feature_id, current_features, :id, :name,
                              {
                                prompt: 'Select a feature',
                                selected: @feature.id,
                              }, {
        data: {
          controller: 'workflows',
          action: 'workflows#featureSelect',
          workflow_id: @workflow.id,
        },
      } %>
    </div>

    <div>
      <%= f.number_field :probability_threshold, step: 'any', value: 0.9 %>
    </div>

    <% if @feature.name == 'resource_feature' %>
      <div>
        <%= f.select :resource_class, %w[Warehouse Feature], { prompt: 'Select a Resource' } %>
      </div>
    <% end %>

    <div>
      <div>
        <%= @feature.id %>
      </div>
      <div>
        <%= @feature.name %>
      </div>
      <div>
        <%= @feature.description %>
      </div>
      <div>
        <% @feature.prompt_decorators.priority_ordered.each do |prompt_decorator| %>
          <p>--------------------------</p>
          <%= prompt_decorator.value %>
        <% end %>
      </div>
    </div>

    <%= f.submit 'Submit' %>
  <% end %>
<% end %>

app/views/workflows/_workflow_features.html.erb
<div class="workflow__container">
  <div class="workflow__playground">
    <div class="workflow__chain-section">
      <%= render "test_prompt_form" %>
      <%= render 'new_feature_section' %>
      <%= render 'workflow_details' %>
    </div>
    <div class="workflow__test-section">
      <%= render 'workflow_output' %>
    </div>
  </div>
</div>

app/views/workflows/_workflow_output.html.erb
<%= turbo_frame_tag "workflow_output_#{@workflow.id}" do %>
  <% if @output.present? %>
    <div>
      <h2>Thread LOG:</h2>
      <% @output[:thread_log].each do |thread_log| %>
        <% thread_log.each do |key, value| %>
            <p>
              <b><%= "#{key}:" %></b>
              <%= value.to_s %>
            </p>
        <% end %>
        <p>-----------------------</p>
      <% end %>
    </div>

    <div>
      <p>-----------------------</p>
      <%= @output[:output] %>
      <p>-----------------------</p>
    </div>
   <% else %>
    </div>
  <% end %>
<% end %>

app/views/workflows/create_feature.turbo_stream.erb
<%= turbo_stream.replace "new_feature_workflow" do %>
  <%= render "new_feature_section" %>
<% end %>

<%= turbo_stream.replace "workflow_features#{@workflow.id}" do %>
  <%= render "workflow_details" %>
<% end %>

app/views/workflows/delete_workflows_feature.turbo_stream.erb
<%= turbo_stream.replace "workflow_features#{@workflow.id}" do %>
  <%= render "workflow_details" %>
<% end %>

app/views/workflows/new_feature.html.erb
<%= turbo_frame_tag @feature do %>
  <%= render 'new_workflow_feature' %>
<% end %>

app/views/workflows/process_input.turbo_stream.erb
<%= turbo_stream.replace "workflow_output_#{@workflow.id}" do %>
  <%= render "workflow_output" %>
<% end %>

app/views/workflows/show.html.erb
<main class="container">
  <div class="header">
    <h1>
      <%= @workflow.name %>
    </h1>
  </div>

  <%= render 'workflow_features' %>
</main>

app/views/workflows/show_feature.html.erb
<%= render 'workflow_feature_form', feature: @feature %>