config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :data_crumbs
  resources :warehouses, only: %i[show]
  resources :workflows, only: %i[show] do
    member do
      get :new_feature
      post :create_feature
      post :process_input
    end
  end
  get 'workflows/:id/features/:feature_id', to: 'workflows#show_feature'
  delete 'workflows/:id/workflows_features/:workflows_feature_id', to: 'workflows#delete_workflows_feature'

  resources :prompt_decorators, only: %i[destroy edit update new create]
  resources :features, only: %i[show]

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount Rupert::API => '/api/'
end

app/views/pages/home.html.erb
<main class="container">
  <h1>Warehouses</h1>
  <div class="home-section-content">
    <% @warehouses.each do |warehouse| %>
      <%= link_to warehouse.name, warehouse, class: 'btn btn--dark' %>
    <% end %>
  </div>

  <h1>Data Crumbs</h1>
  <div class="home-section-content">
    <%= link_to 'All DataCrumbs', data_crumbs_path, class: 'btn btn--dark' %>
  </div>

  <h1>Workflows</h1>
  <div class="home-section-content">
    <% current_user.workflows.each do |workflow| %>
      <%= link_to workflow.name, workflow, class: 'btn btn--dark' %>
    <% end %>
  </div>

  <h1>Conversation Logs</h1>
  <div class="home-section-content">
    <% @conversation_logs.each do |log| %>
      <p> ------------------------ </p>
      <div class="conversation-log">
        <p> <%= log.user_message %> </p>
        <p> <%= log.bot_message %> </p>
      </div>
      <p> ------------------------ </p>
    <% end %>
  </div>
</main>