config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :data_crumbs
  resources :warehouses, only: %i[show]
  resources :workflows, only: %i[show] do
    member do
      get :new_feature
      post :create_feature
      post :process_input
    end
  end
  get 'workflows/:id/features/:feature_id', to: 'workflows#show_feature'
  delete 'workflows/:id/workflows_features/:workflows_feature_id', to: 'workflows#delete_workflows_feature'

  resources :prompt_decorators, only: %i[destroy edit update new create]
  resources :features, only: %i[show]

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount Rupert::API => '/api/'
end

app/models/prompt_decorator.rb
# frozen_string_literal: true

class PromptDecorator < ApplicationRecord
  include Helpers::ValidationHelper

  validates :name, presence: true, uniqueness: true
  validate :name_is_snakecase
  validates :value, presence: true
  validates :priority, presence: true, uniqueness: { scope: :feature_id }

  belongs_to :feature

  scope :priority_ordered, -> { order(:priority) }
end

app/controllers/prompt_decorators_controller.rb
# frozen_string_literal: true

class PromptDecoratorsController < ApplicationController
  before_action :set_prompt_decorator, only: %i[destroy edit update]
  before_action :set_feature

  def new
    @prompt_decorator = PromptDecorator.new
  end

  def edit; end

  def create
    @prompt_decorator = PromptDecorator.new(prompt_decorator_params)

    if @prompt_decorator.save
      @prompt_decorators = @feature.prompt_decorators.priority_ordered

      respond_to do |format|
        notice = t('prompt_decorators.flash.created')
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @prompt_decorator.update(prompt_decorator_params)
      @prompt_decorators = @feature.prompt_decorators.priority_ordered

      respond_to do |format|
        notice = t('prompt_decorators.flash.updated')
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @prompt_decorator.destroy
    respond_to do |format|
      notice = t('prompt_decorators.flash.destroyed')
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def set_prompt_decorator
    @prompt_decorator = PromptDecorator.find(params[:id])
  end

  def set_feature
    feature_id = params[:feature_id] || params[:prompt_decorator].try('[]', :feature_id)

    return if feature_id.blank?

    @feature = Feature.find(feature_id)
  end

  def prompt_decorator_params
    params.require(:prompt_decorator).permit(:value, :name, :feature_id, :priority)
  end
end

app/views/prompt_decorators/_form.html.erb
<%= simple_form_for prompt_decorator, html: { class: 'prompt_decorator form' } do |f| %>
  <% if prompt_decorator.errors.any? %>
    <div class="error-message">
      <%= prompt_decorator.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>


  <div class="prompt-decorator__form">
    <div class="__name_row">
      <div class="__item">
        <p>Name</p>
        <%= f.input :name, input_html: { autofocus: true } %>
      </div>
    </div>
    <div class="__value_row">
      <div class="__item">
        <p>Value</p>
        <%= f.input :value, as: :text %>
      </div>
      <div class="__item">
        <p>Priority</p>
        <%= f.input :priority, as: :text %>
      </div>
    </div>
    <div>
      <%= f.input :feature_id, as: :hidden, input_html: { value: @feature.id } %>
    </div>
    <div>
      <%= link_to 'Cancel', feature_path(@feature), class: 'btn btn--light' %>
      <%= f.submit "#{action_name == 'edit' ? 'Update' : 'Create'} Prompt Decorator", class: 'btn btn--secondary' %>
    </div>
  </div>
<% end %>

app/views/prompt_decorators/_prompt_decorator.html.erb
<%= turbo_frame_tag prompt_decorator do %>
  <div class="warehouse__data_crumb">
    <div class="warehouse__data_crumb__name">
      <%= prompt_decorator.name %>
      <%= prompt_decorator.priority %>
    </div>
    <div>
      <%= simple_format(prompt_decorator.value) %>
    </div>
    <div class="data-crumb__actions">
      <%= button_to 'Delete',
                    prompt_decorator_path(prompt_decorator),
                    method: :delete,
                    form: { data: { turbo_confirm: 'Sure?' } },
                    class: 'btn btn--primary' %>
      <%= link_to 'Edit', edit_prompt_decorator_path(prompt_decorator, feature_id: locals[:feature_id]), class: 'btn btn--light' %>
    </div>
  </div>
<% end %>

app/views/prompt_decorators/_prompt_decorators.html.erb
<%= turbo_frame_tag 'prompt_decorators' do %>
  <%= render @prompt_decorators, locals: { feature_id: @feature.id } %>
<% end %>

app/views/prompt_decorators/create.turbo_stream.erb
<%= turbo_stream.replace "prompt_decorators" do %>
  <%= render "prompt_decorators" %>
<% end %>
<%= turbo_stream.update PromptDecorator.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/prompt_decorators/destroy.turbo_stream.erb
<%= turbo_stream.remove @prompt_decorator %>
<%= render_turbo_stream_flash_messages %>

app/views/prompt_decorators/edit.html.erb
<%= turbo_frame_tag @prompt_decorator do %>
  <%= render 'form', prompt_decorator: @prompt_decorator, locals: { feature_id: @feature.id } %>
<% end %>

app/views/prompt_decorators/new.html.erb
<%= turbo_frame_tag @prompt_decorator do %>
  <%= render 'form', prompt_decorator: @prompt_decorator %>
<% end %>

app/views/prompt_decorators/update.turbo_stream.erb
<%= turbo_stream.replace "prompt_decorators" do %>
  <%= render "prompt_decorators" %>
<% end %>
<%= render_turbo_stream_flash_messages %>